edition = "2021"
version = "Two"
unstable_features = true

tab_spaces = 4
newline_style = "Unix"
wrap_comments = true
imports_granularity = "Crate"
match_block_trailing_comma = true
normalize_comments = true
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true

